[workspace]
members = [
    "network/core",
    "network/sync",
    "network/async",
    "protocols/ouch",
    "protocols/soupbintcp",
    "testing",
]
resolver = "2"


[workspace.dependencies]
# derive
byteserde = { version = "0.3.0", path = "./../byteserde/byteserde" }
byteserde_derive = { version = "0.3.0", path = "./../byteserde/byteserde_derive" }
byteserde_types = { version = "0.3.0", path = "./../byteserde/byteserde_types" }
derive_more = "0.99"                                                               # try_into, etc

# networking
links_network_async = { path = "./network/async" }
links_network_sync = { path = "./network/sync" }
links_network_core = { path = "./network/core" }
bytes = "1.4"

# synch
mio = {version = "0.8", features = ["os-poll" , "net"]}
# rayon = { version = "1.7" }

# async 
tokio = { version = "1.29", features = ["full", "rt-multi-thread"] }
futures = "0.3"                                   # invoke async functions from sync code

# utils
rand = "0.8"
chrono = "0.4.26"
num-format = "0.4"

# logging
log = "0.4"
env_logger = "0.10"
colored =  "2.0"

# protocols
links_soupbintcp_async = { path = "./protocols/soupbintcp" }

# testing only
links_testing = { path = "./testing", features = ["unittest"] }
tokio-test = "0.4.2"
lazy_static = "1.4.0"

# bechmarking only
criterion = "0.5"
