name: Pull/Master Control Build
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-matrix:
    uses: softstream-link/workflows/.github/workflows/maturin-pytest-matrix-toolchain-os.yml@v1
    with:
      toolchain: '["stable"]'
      fail-fast: false
      extension-module-dir: "bindings/python"
  clippy:
    uses: softstream-link/workflows/.github/workflows/maturin-clippy-toolchain.yml@v1
  bench-matrix:
    uses: softstream-link/workflows/.github/workflows/maturin-bench-matrix-toolchain-os.yml@v1
    with:
      fail-fast: false