name: Pull/Master Control Build
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-matrix:
    uses: softstream-link/workflows/.github/workflows/maturin-pytest-matrix-toolchain-os.yml@v1
    with:
      toolchain: '["stable"]'
      fail-fast: false
      maturin-module-dir: "bindings/python"
  clippy:
    uses: softstream-link/workflows/.github/workflows/rust-clippy-toolchain.yml@v1
  bench-matrix:
    uses: softstream-link/workflows/.github/workflows/rust-bench-matrix-toolchain-os.yml@v1
    with:
      fail-fast: false