name: Feature Branch Build On Stable
on:
  push:
     branches:
      - '*'
      - '!master'
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out links current branch
        uses: actions/checkout@v3 # this will checkout current project
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: taiki-e/install-action@nextest
      - name: Testing 
        run: |
          cargo nextest run --all-features # --success-output final
          cargo nextest run --examples --all-features # --success-output final
          cargo test --doc --all-features #  NOTE: docs are not supported by nextest
          cargo doc --all-features # TODO how to fail on warnings?
      - name: Benchmarking
        run: |
          cargo bench --all-features
      - name: Clippy Deny Warnings
        run: |
          cargo clippy --all-features -- --deny warnings
      - name: Publish Dry Run to crates.io
        run: |
          pwd
          ls -la
          pushd core
          cargo publish --dry-run
          popd
          pushd nonblocking
          cargo publish --dry-run
          popd
          pushd blocking
          cargo publish --dry-run
          popd      


    
    



